### ISSUE TITLE
config.json missing

### ISSUE THREAD

**Issue by JindrichSima** [panmourovaty/rustvideoplatform#1]
docker build --tag 'image_name' .
docker run  --tag 'image_name'

Does not create **config.json** file

The readme is missing how to create or retrieve this file.

thread 'main' panicked at src/main.rs:43:82:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by panmourovaty** [comment]
fixed by commit 321d8fe14cf77bb8b198f6301cc672b8d672e3b0
